apiVersion: v1
data:
  profile-name: dev
  user: user@example.com
kind: ConfigMap
metadata:
  name: default-install-config-5cbhhbttg4
---
apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: dev
spec:
  owner:
    kind: User
    name: user@example.com
