# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "cloudlobster-aws-s3"
    encrypt = true
    key     = "terraform_state/do-k8s-challenge/./terraform.tfstate"
    region  = "us-east-1"
  }
}
