apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  dependsOn:
    - name: mpi-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: kubeflow/1.4/dev
  prune: false
  interval: 1m0s
