apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-namespace
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: kubeflow/1.4/istio/namespace
  prune: false
  interval: 1m0s