apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubeflow-prereqs
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: kubeflow/prereqs
  prune: true
  interval: 1m0s